spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
